<?php $this->useLayout($admin_layout) ?>
<?php $this->startBlock('content') ?>
    <div class="page-head">
        <h1>Media</h1>
        <span class="spacer"></span>
        <?php if (!empty($trash)): ?>
            <?= $this->fetch('dpress_admin:trash-button', $trash) ?>
        <?php endif ?>
        <?php if (!empty($can_upload)): ?>
            <a class="button primary with-icon" href="<?= esc_attr($upload_url) ?>"><?= \Dynart\Dpress\Dpress::icon('upload') ?> Upload</a>
        <?php endif ?>
    </div>

    <?= $this->fetch('dpress_admin:list', [
        'list_id' => $list_id,
        'list_config' => $list_config,
        'filters' => $this->fetch('dpress_admin:media/filters', ['categories' => $categories]),
    ]) ?>
<?php $this->endBlock() ?>
