<?php $this->useLayout($admin_layout) ?>
<?php $this->startBlock('content') ?>
    <div class="page-head">
        <h1>Users</h1>
        <span class="spacer"></span>
        <?php if (!empty($can_create)): ?>
            <a class="button primary with-icon" href="<?= esc_attr($new_url) ?>"><?= \Dynart\Dpress\Dpress::icon('plus') ?> New</a>
        <?php endif ?>
    </div>

    <?= $this->fetch('dpress_admin:list', [
        'list_id' => $list_id,
        'list_config' => $list_config,
        'filters' => $this->fetch('dpress_admin:user/filters', ['statuses' => $statuses]),
    ]) ?>
<?php $this->endBlock() ?>
